# Generated by Django 3.0.2 on 2020-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('jerusalem', 'Jerusalem'), ('tel_aviv', 'Tel Aviv')], max_length=120),
        ),
    ]
