# Generated by Django 3.0.2 on 2020-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200316_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_symbol', models.IntegerField()),
                ('city_name_hebrew', models.CharField(max_length=240, unique=True)),
                ('city_name_english', models.CharField(max_length=240)),
                ('city_name_transcription', models.CharField(max_length=240)),
                ('district', models.CharField(max_length=240)),
                ('subdistrict_name', models.CharField(max_length=240)),
                ('subdistrict_symbol', models.IntegerField(default='2018')),
                ('data_year', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=120),
        ),
    ]
