# Generated by Django 3.0.2 on 2020-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20200318_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='data_year',
            field=models.IntegerField(default='2018'),
        ),
        migrations.AlterField(
            model_name='city',
            name='subdistrict_symbol',
            field=models.IntegerField(),
        ),
    ]
