# Generated by Django 3.0.2 on 2020-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('datetime_event', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(max_length=6)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('datetime_event', models.CharField(max_length=100)),
                ('location', models.TextField(max_length=200)),
                ('price', models.FloatField(max_length=15)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('eaddress', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=15)),
                ('num_of_people', models.CharField(max_length=15)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField()),
                ('registration_status', models.CharField(choices=[('submitted', 'submitted'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='submitted', max_length=20)),
            ],
        ),
    ]
