# Generated by Django 3.0.2 on 2020-02-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRegistrations',
            new_name='EventRegistration',
        ),
    ]
