# Generated by Django 3.0.2 on 2020-02-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200213_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
