# Generated by Django 3.0.2 on 2020-04-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersweb', '0003_auto_20200415_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderweb',
            name='cart',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
