# Generated by Django 3.0.2 on 2020-04-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('ordersweb', '0004_auto_20200416_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderweb',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
    ]
