# Generated by Django 3.0.2 on 2020-04-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersweb', '0006_auto_20200416_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderweb',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='orderweb',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='orderweb',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
