# Generated by Django 3.0.2 on 2020-04-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersweb', '0007_auto_20200420_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderweb',
            name='age_above_18',
            field=models.BooleanField(default=True),
        ),
    ]
