# Generated by Django 3.0.2 on 2020-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersweb', '0008_orderweb_age_above_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderweb',
            name='approve_terms',
            field=models.BooleanField(default=True),
        ),
    ]
