# Generated by Django 3.0.2 on 2020-02-27 11:40

from django.db import migrations, models
import django.db.models.deletion
import purchases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, unique=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer')], max_length=200)),
                ('actual_payment_date', models.DateField(blank=True)),
                ('receipt_copy', models.ImageField(blank=True, null=True, upload_to=purchases.models.upload_image_path)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('vendor', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
        ),
    ]
