# Generated by Django 3.0.2 on 2020-04-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200303_1711'),
        ('vendors', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
    ]
