# Generated by Django 3.0.2 on 2020-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('business_address', models.CharField(blank=True, max_length=300, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('web_site', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
