# Generated by Django 3.0.2 on 2020-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('wine', 'Wine'), ('beer', 'Beer'), ('alcohol', 'Alcohol'), ('other', 'Other')], max_length=200),
        ),
    ]
