# Generated by Django 3.0.2 on 2020-04-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ml',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
