# Generated by Django 3.0.2 on 2020-02-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('products', '0006_auto_20200211_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('wine', 'Wine'), ('beer', 'Beer'), ('alcohol', 'Alcohol')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=2, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(default='2020'),
        ),
    ]
