# Generated by Django 3.0.2 on 2020-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200219_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('wine', 'Wine'), ('beer', 'Beer'), ('alcohol', 'Alcohol')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, default='2020'),
        ),
    ]
