# Generated by Django 3.0.2 on 2020-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200424_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, default='2020', null=True),
        ),
    ]
