# Generated by Django 3.0.2 on 2020-02-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
    ]
