# Generated by Django 3.0.2 on 2020-02-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200219_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcohol_pre',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='grapes_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
